#! /usr/bin/env bash

if [[ -n "$@" ]]; then
    res=$(git -C "$1" clone "$2" --depth=1 --recursive 2>&1)
    if [[ $? -ne 0 ]]; then
        regex="fatal: destination path '([^']+)'.*" 
        if [[ $res =~ $regex ]]; then
            dir="${BASH_REMATCH[1]}"
            git -C "$1/$dir" pull
        fi
    fi
else
    xargs -n 2 -P 20 -a plugins.txt ./install_or_update_plugins
fi
