#! /usr/bin/env bash

configure_git() {
    git config --global core.editor "nvim -c 'startinsert'"
    git config --global core.pager "perl /usr/share/doc/git/contrib/diff-highlight/diff-highlight | less"
    git config --global core.excludesfile "~/.gitignore_global"
    git config --global mergetool.vimdiff.cmd "nvim -d \$BASE \$MERGED \$REMOTE \$LOCAL -c 'wincmd w' -c 'wincmd J'"
    git config --global mergetool.prompt "true"
    git config --global merge.tool "vimdiff"
    git config --global diff.tool "vimdiff"
    git config --global difftool.vimdiff.cmd "nvim -d \$BASE \$LOCAL -O"
    git config --global difftool.prompt "true"
    git config --global difftool.path "vimdiff"
    git config --global diff.wordRegex "(\w+)|([^[:space:]])"
    git config --global alias.wd "diff --word-diff=color"
    git config --global alias.d "difftool"
    git config --global alias.a "!sh -c 'git add -- \"$@\" && git status' --"
    git config --global alias.lg "log --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr)%Creset' --abbrev-commit --date=relative"
    git config --global pager.log "true"
    git config --global pager.show "true"
    git config --global pager.diff "true"

    git config --global filter.no_breakpoints.clean 'sed -E "/pdb/d;/^\s*breakpoint\(\)/d"'
}

function install_or_update_plugin() {
    res=$(git -C "$1" clone "$2" --depth=1 --recursive 2>&1)
    if [[ $? -ne 0 ]]; then
        regex="fatal: destination path '([^']+)'.*" 
        if [[ $res =~ $regex ]]; then
            dir="${BASH_REMATCH[1]}"
            git -C "$1/$dir" pull
        fi
    fi
}

case "$1" in
    plugin) shift; install_or_update_plugin $@ ;;
    git) configure_git ;;
    *) xargs -n 2 -P 20 -a plugins.txt ./provision plugin ;;
esac
